"""VLAN discovery: vlans, vlan_interfaces, sync_runs, sync_run_switches

Milestone 2. Discovery data plus synchronisation history.

Design points worth knowing before altering this schema:

* `vlans` is unique on **(switch_id, vlan_id)**, not `vlan_id`. The same 802.1Q
  tag legitimately exists on many switches; answering "who is using 1234" means
  aggregating rows across switches.
* **No `is_available` column.** Availability is derived at query time from the
  absence of an active row. A stored flag would drift from the switches, which is
  exactly what this service exists to prevent.
* **Removals are soft** — `state` moves 'active' -> 'missing' and history is
  preserved. Discovery data is an audit trail, and a VLAN can reappear.
* `vlans.vlan_id` is the 802.1Q tag; `vlans.id` is the surrogate key. Hence
  `vlan_interfaces.vlan_record_id`, named to keep the two unambiguous.
* `sync_run_switches` keeps `switch_name` as a snapshot and nulls `switch_id` on
  switch deletion, so run history stays auditable across inventory changes.
* Enum-backed columns (`state`, `mode`, `trigger`, `status`, `outcome`) are plain
  strings with no CHECK constraint, matching the `switches.vendor` precedent:
  the application owns the allowed values, so adding one needs no migration.

Revision ID: 0002_vlan_discovery
Revises: 0001_initial
Create Date: 2026-08-04
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_vlan_discovery"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("switches_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("switches_succeeded", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("switches_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("switches_skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_discovered", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "vlans_marked_missing", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    op.create_index("ix_sync_runs_started_at", "sync_runs", ["started_at"], unique=False)
    op.create_index("ix_sync_runs_status", "sync_runs", ["status"], unique=False)
    op.create_table(
        "sync_run_switches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_run_id", sa.Integer(), nullable=False),
        sa.Column("switch_id", sa.Integer(), nullable=True),
        sa.Column("switch_name", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("vlans_discovered", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("vlans_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "vlans_marked_missing", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
            name=op.f("fk_sync_run_switches_switch_id_switches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_sync_run_switches_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run_switches")),
    )
    op.create_index(
        "ix_sync_run_switches_sync_run_id", "sync_run_switches", ["sync_run_id"], unique=False
    )
    op.create_table(
        "vlans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("switch_id", sa.Integer(), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("l3_interface", sa.String(length=100), nullable=True),
        sa.Column("vxlan_vni", sa.Integer(), nullable=True),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("vlan_id >= 1 AND vlan_id <= 4094", name=op.f("ck_vlans_vlan_id_range")),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["switches.id"],
            name=op.f("fk_vlans_switch_id_switches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vlans")),
        sa.UniqueConstraint("switch_id", "vlan_id", name="uq_vlans_switch_id_vlan_id"),
    )
    op.create_index("ix_vlans_name", "vlans", ["name"], unique=False)
    op.create_index("ix_vlans_state", "vlans", ["state"], unique=False)
    op.create_index("ix_vlans_switch_id_state", "vlans", ["switch_id", "state"], unique=False)
    op.create_index("ix_vlans_vlan_id_state", "vlans", ["vlan_id", "state"], unique=False)
    op.create_table(
        "vlan_interfaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vlan_record_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "mode", sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vlan_record_id"],
            ["vlans.id"],
            name=op.f("fk_vlan_interfaces_vlan_record_id_vlans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vlan_interfaces")),
        sa.UniqueConstraint(
            "vlan_record_id", "name", name="uq_vlan_interfaces_vlan_record_id_name"
        ),
    )
    op.create_index("ix_vlan_interfaces_name", "vlan_interfaces", ["name"], unique=False)
    op.create_index(
        "ix_vlan_interfaces_vlan_record_id", "vlan_interfaces", ["vlan_record_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vlan_interfaces_vlan_record_id", table_name="vlan_interfaces")
    op.drop_index("ix_vlan_interfaces_name", table_name="vlan_interfaces")
    op.drop_table("vlan_interfaces")
    op.drop_index("ix_vlans_vlan_id_state", table_name="vlans")
    op.drop_index("ix_vlans_switch_id_state", table_name="vlans")
    op.drop_index("ix_vlans_state", table_name="vlans")
    op.drop_index("ix_vlans_name", table_name="vlans")
    op.drop_table("vlans")
    op.drop_index("ix_sync_run_switches_sync_run_id", table_name="sync_run_switches")
    op.drop_table("sync_run_switches")
    op.drop_index("ix_sync_runs_status", table_name="sync_runs")
    op.drop_index("ix_sync_runs_started_at", table_name="sync_runs")
    op.drop_table("sync_runs")
    # ### end Alembic commands ###
